# Ganti dengan key dari dashboard SonarCloud Anda
sonar.projectKey=nama-project-anda
sonar.organization=nama-org-anda

sonar.sources=.
sonar.exclusions=**/node_modules/**,**/dist/**,**/.venv/**,**/__pycache__/**

# Mencegah memory leak saat scanning lokal/remote
sonar.javascript.node.maxspace=4096
sonar.python.version=3.10